// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyADWalUtq_ysAX_RWy1SoYxycgWq2Kh8cw',
    appId: '1:947983809243:web:3ccb1eac3b2a04e96aaafe',
    messagingSenderId: '947983809243',
    projectId: 'interactive-care',
    authDomain: 'interactive-care.firebaseapp.com',
    storageBucket: 'interactive-care.appspot.com',
    measurementId: 'G-DJ15M0S7ED',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBlJp4bpmcztcut7qAzqGsSKAz1VRKzzEQ',
    appId: '1:947983809243:android:f0ab6b37a29e76716aaafe',
    messagingSenderId: '947983809243',
    projectId: 'interactive-care',
    storageBucket: 'interactive-care.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC9fQqp5P0wee8YVexjuBRUXPOkR4bB0kw',
    appId: '1:947983809243:ios:d0f5afc3beab55966aaafe',
    messagingSenderId: '947983809243',
    projectId: 'interactive-care',
    storageBucket: 'interactive-care.appspot.com',
    iosBundleId: 'com.example.interactiveCare',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC9fQqp5P0wee8YVexjuBRUXPOkR4bB0kw',
    appId: '1:947983809243:ios:717682768f2dfd876aaafe',
    messagingSenderId: '947983809243',
    projectId: 'interactive-care',
    storageBucket: 'interactive-care.appspot.com',
    iosBundleId: 'com.example.interactiveCare.RunnerTests',
  );
}
